### ISSUE TITLE
Any chance it can be made working with iNav?

### ISSUE THREAD

**Issue by 0crap** [bsondermann/BlackboxSticksExporter#3]
Thx!

**Comment by bsondermann** [comment]
Can you send me an iNav log to my email?
bastian.sondermann@web.de

**Comment by 0crap** [comment]
Done!

**Comment by bsondermann** [comment]
I will take a look asap.

**Comment by bsondermann** [comment]
Hi, I think it should work now. I will make a new release in a few days when I have done some minor improvements but for now you can download it of my google drive.
https://drive.google.com/file/d/1PohYm4GFjW2eEHyHMK9PksILDGK384kb/view?usp=sharing
let me know if problems occur.
Thanks and stay safe!

**Comment by 0crap** [comment]
Great! I gave it a few large iNav files without issues.

Only issue I found if it's done with one file and you select a different input folder, with the check "export to input folder", it did found 2 logs, but when you hit Start nothing happens.
Close the app and start again solves it.

Thx for your time!
I'll close this one, because this issue will be available in your next release,
