### ISSUE TITLE
V4.4 Win64 Hangs

### ISSUE THREAD

**Issue by gdmckee** [bsondermann/BlackboxSticksExporter#4]
Not having any luck with the app.  Downloaded 4.4-win64 and it starts off fine and you can see the sticks moving in the rendering window, then the sticks stop moving and it just hangs.  Are they any debug logs I can see what is causing it to crash?  Everything on defaults.  Tried with a number of logs and the logs open fine in BB.
![BBBSV4 4](https://user-images.githubusercontent.com/60676576/97164779-8d5c0880-177a-11eb-8477-6764004cee37.PNG)

**Comment by bsondermann** [comment]
try enabling the logger in the top right and then start the rendering. 2 logs should appear in the /assets/logs directory. Please send them to me :D

**Comment by gdmckee** [comment]
Hi

Thanks - it got further but hung. 
![BBBSV4 4-Debug](https://user-images.githubusercontent.com/60676576/97190289-7549b080-179d-11eb-861b-44b4ea0c996c.PNG)
[log.txt](https://github.com/bsondermann/BlackboxSticksExporter/files/5439602/log.txt)

The other debug file is 1.3GB!!  It seams to start with:

map(0, 0, 0, 0, 700) called, which returns NaN (not a number)
map(0, 0, 0, 0, 100) called, which returns NaN (not a number)
java.lang.NullPointerException
	at java.util.LinkedList.get(LinkedList.java:477)
	at BlackboxSticksExporter$ImageExporter.run(BlackboxSticksExporter.java:2127)
java.lang.NullPointerException
	at java.util.LinkedList.get(LinkedList.java:477)
	at BlackboxSticksExporter$ImageExporter.run(BlackboxSticksExporter.java:2127)
java.lang.NullPointerException
	at java.util.LinkedList.get(LinkedList.java:477)
	at BlackboxSticksExporter$ImageExporter.run(BlackboxSticksExporter.java:2127)
java.lang.NullPointerException 

for about 100k lines, then the rest is of the log is:
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException

Thanks

**Comment by bsondermann** [comment]
can you send me the .bfl log too?

**Comment by gdmckee** [comment]
[LOG00224.zip](https://github.com/bsondermann/BlackboxSticksExporter/files/5439891/LOG00224.zip)

**Comment by bsondermann** [comment]
wtf it works perfectly fine for me... try moving the log to another directory (e.g. documents), maybe the program doesnt have the permissions to write to that directory.

**Comment by gdmckee** [comment]
Moving the dir into the Downloads folder worked!!  Very strange!  Thanks for all your help.
